### ISSUE TITLE
Modal inside another modal

### ISSUE THREAD

**Issue by fabio-barboza** [logbon72/angular-material-datetimepicker#75] opened 2016-10-31 18:56 UTC
Greetings,

Is it possible to add this parameter "skipHide: true" in the $mdDialog.show call?

              $mdDialog.show({
                  template: template,
                  controller: PluginController,
                  controllerAs: 'picker',
                  locals: locals,
                  openFrom: element,
                  parent: angular.element(document.body),
                  bindToController: true,
                  disableParentScroll: false,
                  skipHide: true
                })

This gonna make possible to show the DatePicker modal inside of another modal.

Regards,

Fabio

**Comment by blaszek222** [comment] 2016-11-17 17:23
I think this is the duplicate of #60

**Comment by logbon72** [comment] 2017-02-04 19:44
Fixed in most recent update.

**Closed as completed by logbon72** 2017-02-04 19:44 UTC
